### ISSUE TITLE
Request: Discussion on your this repo.

### ISSUE THREAD

**Issue by faisalshahbaz** [Ashwin-Ramesh2607/DeepSort-YOLOv3#1]
Hey @Ashwin-Ramesh2607 

Hope you doing well, I love your work especially this repo. I am working same type of project with some modification. I need your lil help. Please connect with me on Linkedin. I will share my repo with you.

https://www.linkedin.com/in/faisalshahbaz/

**Comment by Ashwin-Ramesh2607** [comment]
Hey,

Sure, i have sent the LinkedIn connection request.

Thanks,
Ashwin Ramesh
